% -------------------------------------------------------------------
%  Generated by MATLAB on 4-Jan-2025 18:22:38
%  MATLAB version: 9.10.0.1602886 (R2021a)
% -------------------------------------------------------------------
saveVarsMat = load('UAV_PID_PROJ.mat');

Kd = 1;

Ki = 2;

Kp = 2;

closedLoop = saveVarsMat.closedLoop; % <1x1 tf> unsupported class

controller = saveVarsMat.controller; % <1x1 pid> unsupported class

den = [1.5 0 0];

desired_altitude = 13;

disturbance = saveVarsMat.disturbance; % <1x1 tf> unsupported class

disturbedSystem = saveVarsMat.disturbedSystem; % <1x1 tf> unsupported class

g = 9.81;

info = struct;
info.RiseTime = 0.54625590940898006;
info.SettlingTime = 32.203462137655166;
info.SettlingMin = 0.43043559857644759;
info.SettlingMax = 1.6438277612470473;
info.Overshoot = 64.382776124704733;
info.Undershoot = -0;
info.Peak = 1.6438277612470473;
info.PeakTime = 1.5841867670431531;

m = 1.5;

num = 2;

sys = saveVarsMat.sys; % <1x1 tf> unsupported class

clear saveVarsMat;
